// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bind_local_listener`, `connect_to_proxy_node`, `connect_via_chain`, `handle_inbound_client`, `read_socks5_frame`, `run_local_proxy`, `socks5_accept_client`, `socks5_connect`, `socks5_handshake`, `validate_proxy_node`, `validate_proxy_protocol`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Socks5Frame`, `TargetAddr`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

ProxyChain createMockChain() =>
    RustLib.instance.api.crateApiProxyCreateMockChain();

void startLocalProxy({required ProxyChain chain, required int localPort}) =>
    RustLib.instance.api.crateApiProxyStartLocalProxy(
      chain: chain,
      localPort: localPort,
    );

class ProxyChain {
  final ProxyNode entryNode;
  final ProxyNode exitNode;

  const ProxyChain({required this.entryNode, required this.exitNode});

  @override
  int get hashCode => entryNode.hashCode ^ exitNode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyChain &&
          runtimeType == other.runtimeType &&
          entryNode == other.entryNode &&
          exitNode == other.exitNode;
}

class ProxyNode {
  final String id;
  final String name;
  final ProxyProtocol protocol;
  final String server;
  final int port;
  final String password;
  final String? cipher;

  const ProxyNode({
    required this.id,
    required this.name,
    required this.protocol,
    required this.server,
    required this.port,
    required this.password,
    this.cipher,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      protocol.hashCode ^
      server.hashCode ^
      port.hashCode ^
      password.hashCode ^
      cipher.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          protocol == other.protocol &&
          server == other.server &&
          port == other.port &&
          password == other.password &&
          cipher == other.cipher;
}

enum ProxyProtocol { shadowsocks, trojan, socks5, vmess }
