// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'proxy.dart';

// These functions are ignored because they are not marked as `pub`: `decode_fragment`, `decode_percent`, `decode_ss_userinfo`, `decode_subscription_blob`, `looks_like_clash_yaml`, `parse_base64_sub`, `parse_clash_yaml`, `parse_proxy_uri`, `parse_socks5_uri`, `parse_ss_uri`, `parse_subscription_text`, `parse_trojan_uri`, `parse_vmess_uri`, `split_host_port`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ClashConfig`, `ClashProxy`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`

List<ProxyNode> fetchSubscription({required String url}) =>
    RustLib.instance.api.crateApiSubscriptionFetchSubscription(url: url);
