// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'proxy.dart';

// These functions are ignored because they are not marked as `pub`: `setup_routes`

Future<void> startTun({
  required ProxyChain chain,
  required SenderTrafficMsg tx,
}) => RustLib.instance.api.crateApiTunProxyStartTun(chain: chain, tx: tx);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Sender < TrafficMsg >>>
abstract class SenderTrafficMsg implements RustOpaqueInterface {}
